name: CI

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install deps
        run: |
          python -m pip install -U pip setuptools wheel
          pip install --no-build-isolation -r requirements.txt
          pip install pytest

      - name: Lint & format
        run: |
          pip install black ruff isort
          black --check .
          ruff check .
          isort --check-only .

      - name: Run tests
        run: pytest -q
